<x-app-layout>
    <x-slot name="header">Input Manual</x-slot>

    <div class="max-w-4xl mx-auto space-y-6">
        <x-ui.card>
            <x-ui.card-header>
                <div class="flex items-center justify-between">
                    <div>
                        <x-ui.card-title>{{ $answerKey->nama }}</x-ui.card-title>
                        <x-ui.card-description>{{ $answerKey->mata_pelajaran }} • {{ $answerKey->jumlah_soal }}
                            soal</x-ui.card-description>
                    </div>
                    <a href="{{ route('ljk.correction.scan', $answerKey) }}" class="btn btn-secondary btn-sm">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z">
                            </path>
                        </svg>
                        Scan dengan Kamera
                    </a>
                </div>
            </x-ui.card-header>
            <x-ui.card-content>
                <form action="{{ route('ljk.correction.process') }}" method="POST" id="correctionForm">
                    @csrf
                    <input type="hidden" name="ljk_answer_key_id" value="{{ $answerKey->id }}">

                    <!-- Student Info -->
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                        <div>
                            <label for="nama_peserta" class="label">Nama Peserta</label>
                            <input type="text" name="nama_peserta" id="nama_peserta" class="input w-full"
                                placeholder="Nama siswa">
                        </div>
                        <div>
                            <label for="nomor_peserta" class="label">Nomor Peserta</label>
                            <input type="text" name="nomor_peserta" id="nomor_peserta" class="input w-full"
                                placeholder="No. peserta">
                        </div>
                        <div>
                            <label for="kelas" class="label">Kelas</label>
                            <input type="text" name="kelas" id="kelas" class="input w-full"
                                value="{{ $answerKey->kelas }}" placeholder="Kelas">
                        </div>
                    </div>

                    <!-- Answer Grid -->
                    <div class="mb-6">
                        <label class="label mb-3">Jawaban Siswa</label>
                        <p class="text-sm text-[hsl(var(--muted-foreground))] mb-4">Klik pada pilihan jawaban yang diisi
                            siswa. Klik lagi untuk membatalkan.</p>

                        <div class="bg-[hsl(var(--muted)/.3)] border rounded-lg p-4">
                            <div id="studentAnswerGrid" class="grid grid-cols-5 md:grid-cols-10 gap-2">
                                <!-- Generated by JS -->
                            </div>
                        </div>
                    </div>

                    <!-- Submit -->
                    <div class="flex items-center justify-between pt-4 border-t">
                        <p class="text-sm text-[hsl(var(--muted-foreground))]" id="progressText">0 dari
                            {{ $answerKey->jumlah_soal }} jawaban diisi</p>
                        <div class="flex items-center gap-2">
                            <a href="{{ route('ljk.correction.index') }}" class="btn btn-secondary">Batal</a>
                            <button type="submit" class="btn btn-primary">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                                Koreksi Jawaban
                            </button>
                        </div>
                    </div>
                </form>
            </x-ui.card-content>
        </x-ui.card>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const jumlahSoal = {{ $answerKey->jumlah_soal }};
            const jumlahPilihan = {{ $answerKey->jumlah_pilihan }};
            const optionLabels = ['A', 'B', 'C', 'D', 'E'].slice(0, jumlahPilihan);
            const studentAnswerGrid = document.getElementById('studentAnswerGrid');
            const progressText = document.getElementById('progressText');

            function generateAnswerGrid() {
                studentAnswerGrid.innerHTML = '';

                for (let i = 1; i <= jumlahSoal; i++) {
                    const itemDiv = document.createElement('div');
                    itemDiv.className = 'bg-white border rounded p-2 text-center';

                    const numberDiv = document.createElement('div');
                    numberDiv.className = 'font-bold text-sm mb-1';
                    numberDiv.textContent = i;
                    itemDiv.appendChild(numberDiv);

                    const optionsDiv = document.createElement('div');
                    optionsDiv.className = 'flex justify-center gap-1 flex-wrap';

                    for (let j = 0; j < jumlahPilihan; j++) {
                        const optionBtn = document.createElement('button');
                        optionBtn.type = 'button';
                        optionBtn.className =
                            'w-6 h-6 text-xs border rounded hover:bg-primary hover:text-white transition-colors answer-option';
                        optionBtn.textContent = optionLabels[j];

                        optionBtn.addEventListener('click', function() {
                            const wasSelected = this.classList.contains('bg-primary');

                            itemDiv.querySelectorAll('.answer-option').forEach(btn => {
                                btn.classList.remove('bg-primary', 'text-white');
                            });

                            const input = document.getElementById(`student_answer_${i}`);

                            if (wasSelected) {
                                input.value = '';
                            } else {
                                this.classList.add('bg-primary', 'text-white');
                                input.value = optionLabels[j];
                            }

                            updateProgress();
                        });

                        optionsDiv.appendChild(optionBtn);
                    }

                    const hiddenInput = document.createElement('input');
                    hiddenInput.type = 'hidden';
                    hiddenInput.name = `jawaban_siswa[${i - 1}]`;
                    hiddenInput.id = `student_answer_${i}`;
                    itemDiv.appendChild(hiddenInput);

                    itemDiv.appendChild(optionsDiv);
                    studentAnswerGrid.appendChild(itemDiv);
                }
            }

            function updateProgress() {
                const filled = document.querySelectorAll('.answer-option.bg-primary').length;
                progressText.textContent = `${filled} dari ${jumlahSoal} jawaban diisi`;
            }

            generateAnswerGrid();
        });
    </script>
</x-app-layout>
