<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Rpp;
use Illuminate\View\View;

class RppController extends Controller
{
    /**
     * Display all RPPs generated by guru accounts.
     */
    public function index(): View
    {
        $rpps = Rpp::with('user')
            ->whereHas('user', fn ($q) => $q->where('role', 'guru'))
            ->latest()
            ->paginate(15);

        return view('admin.rpp.index', compact('rpps'));
    }
}
